### ISSUE TITLE
Switch navigo links

### ISSUE THREAD

**Issue by inezabonte** [Ginab972/Hacker-News#2]
https://github.com/Ginab972/Hacker-News/blob/33779e2098cdab2c8fd4123a02d64f5eca636d0d/index.html#L29-L30
- The link referencing to the `app.js` file should come before the one for navigo cdn
- I'd suggest for you to use this link below since I tested it and I know it works
```html
<script src="https://unpkg.com/navigo@6.0.2/lib/navigo.min.js"></script>
```

**Comment by Ginab972** [comment]
That fixed my issue. Thank You so much for your help!!!!
