### ISSUE TITLE
view import issue

### ISSUE THREAD

**Issue by inezabonte** [Ginab972/Hacker-News#3]
https://github.com/Ginab972/Hacker-News/blob/33779e2098cdab2c8fd4123a02d64f5eca636d0d/pages/stories.js#L2

This import statement gave me issues while working on it in vscode. 
I'm guessing the scrimba platform handles it differently.

Anyway, I replaced it with the code below and that fixed it.
```js
const view = document.querySelector("#router-outlet");
```

**Comment by Ginab972** [comment]
I have it working now, I have updated all the code. Thank You so much for the help.
